[tool.poetry]
    name = "seis-606"
    version = "0.1.0"
    description = "SEIS-606 Coursework & Assignments"
    authors = ["Dante Razo <razo3843@stthomas.edu>"]
    readme = "README.md"
    package-mode = false

[tool.poetry.dependencies]
    python = ">=3.14"

    # common
    ipykernel = "*"
    jupyter = "*"
    nbconvert = "*"
    pylance = "*"
    ruff = "*"
    torch = { version = "*", source = "torch-cuda" } # torch w/ GPU acceleration
    dotenv = "*"

    # first used in hw2
    diffusers = "*"


[[tool.poetry.source]]
    name = "pypi"
    priority = "primary"


# for desktop
[[tool.poetry.source]]
    name = "torch-cuda"
    url = "https://download.pytorch.org/whl/cu130"
    priority = "explicit"

# for server
[[tool.poetry.source]]
    name = "torch-rocm"
    url = "https://download.pytorch.org/whl/rocm7.0"
    priority = "explicit"

[build-system]
    requires = ["poetry-core"]
    build-backend = "poetry.core.masonry.api"

[tool.ruff]
    line-length = 150
    exclude = [".git", ".venv"]
